server:
  port: ${SERVER_PORT:8744}
spring:
  application:
    name: ms-course
  zipkin:
    base-url: ${ZIPKIN_URI:http://localhost:9411}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8763/eureka}
  instance:
    leaseRenewalIntervalInSeconds: 4
    leaseExpirationDurationInSeconds: 8