server:
  port: 8743
spring:
  application:
    name: ms-course

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8763/eureka
  instance:
    leaseRenewalIntervalInSeconds: 4
    leaseExpirationDurationInSeconds: 8