
###CREAR NUEVO CURSO

POST http://localhost:8743/v1/api/course
Content-Type: application/json

{
  "teacherId": 1,
  "studentId": 5,
  "course": 1,
  "gradeDescription":"Advanced grade"
}

### OBTENER ESTUDIANTES POR CURSO
GET http://localhost:8743/v1/api/course/students/2
Accept: application/json

###
